name: allure-junit5-maven

on:
  workflow_dispatch:

env:
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  CHAT_ID: ${{ secrets.CHAT_ID }}
  TOKEN: ${{ secrets.TOKEN }}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run Test
        if: always()
        run: printenv && pytest tests/prod --alluredir=allure-results && ls allure-results
        continue-on-error: true

      - name: Get Allure history
        uses: actions/checkout@v4.1.1
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: target/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history


      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4.1.4
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4.0.4