name: second

on:
#  workflow_dispatch:
  schedule:
    - cron: "05 11 * * *"
  pull_request:

env:
  QASE_REPORT: 1
  QASE_PROJECT_CODE: DEMO
  QASE_RUN_COMPLETE: true
  QASE_TESTOPS_API_TOKEN: ${{ secrets.QASE_TESTOPS_API_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: tests
        run: pytest
        continue-on-error: false


